name: Publish mylog crate

on:
  push:
    branches: [main]
    # Optionnel : déclencher seulement quand mylog change
    paths:
      - 'mylog/**'
      - '.github/workflows/publish-mylog.yml'

jobs:
  publish-mylog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal

      - name: Run tests for mylog
        run: cargo test -p mylog

      - name: Publish mylog to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo publish -p mylog
