name: Publish mylog crate

on:
  push:
    branches: [main]
    paths:
      - 'mylog/**'
      - 'README.md'  # Déclencher aussi quand le README change
      - '.github/workflows/publish-mylog.yml'

jobs:
  publish-mylog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify README path
        run: |
          # Vérifier que le chemin existe
          cd mylog
          if [ ! -f "../README.md" ]; then
            echo "❌ ERREUR: README.md introuvable à la racine"
            exit 1
          fi

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Run tests
        run: cargo test -p mylog

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          # Publier depuis le dossier mylog
          cd mylog
          cargo publish
